<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Aula extends Model
{
    //
    protected $table = 'aulas';
    protected $fillable = [
        'numero',
        'semestre_id',
        'profesor_id',
    ];

    protected static function booted()
    {
        // parent::booted(); // TODO: Change the autogenerated stub
        static::creating(function ($aula) {
            // Calcula el número siguiente dentro del semestre
            $ultimoNumero = static::where('semestre_id', $aula->semestre_id)
                ->max('numero');

            $aula->numero = $ultimoNumero ? $ultimoNumero + 1 : 1;
        });
    }

    public function semestre() {
        return $this->belongsTo(Semestre::class, 'semestre_id', 'id');
    }

    public function profesor() {
        return $this->belongsTo(Profesor::class, 'profesor_id', 'id');
    }

    // Relación con alumnos
    public function alumnos() {
        return $this->hasMany(Alumno::class);
    }

    public function entregas()
    {
        return $this->hasMany(Entrega::class);
    }

}
