<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Semestre extends Model
{
    //
    protected $table = 'semestres';
    protected $fillable = [
        'nombre',
        'activo',
    ];

    protected static function booted()
    {
        //parent::booted(); // TODO: Change the autogenerated stub
        static::saving(function ($semestre) {

            // Si este semestre se activa
            if ($semestre->activo) {
                // Desactivar todos los demás
                static::where('id', '!=', $semestre->id)
                    ->update(['activo' => false]);
            }
        });
    }

    public function aula() {
        return $this->hasOne(Aula::class, 'aula_id', 'id');
    }
}
